stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  REGISTRY: $CI_REGISTRY
  IMAGE: $CI_REGISTRY_IMAGE
  BRANCH_TAG: $CI_COMMIT_BRANCH
  COMMIT_TAG: $CI_COMMIT_SHA

build:
  stage: build
  tags:
    - docker
    - shell
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -f Dockerfile -t $IMAGE:$COMMIT_TAG .
    - docker push $IMAGE:$COMMIT_TAG
    - docker tag $IMAGE:$COMMIT_TAG $IMAGE:$BRANCH_TAG
    - docker push $IMAGE:$BRANCH_TAG
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - main
    - dev


deploy-dev:
  stage: deploy
  tags:
    - shell
  before_script:
    - which curl || apt-get update && apt-get install -y curl
  script: curl -k -X POST "https://78.40.109.183:9443/api/stacks/webhooks/ca05194e-f54f-4a44-81fa-af3702cdbaa3"
  needs:
    - build
  only:
    - dev
