services:
  front:
    build: 
      context: .
      args:
        - VITE_BASE_API_URL=${VITE_BASE_API_URL}
        - IMAGE_REGISTRY_URL=${IMAGE_REGISTRY_URL}
    ports:
      - "8088:80"
    env_file:
      - stack.env
#    deploy:
#     replicas: 1
#     restart_policy:
#       condition: on-failure
#     placement:
#       constraints:
#         - node.role == worker