services:
  front:
    build: .
    ports:
      - "8088:80"
    env_file:
      - stack.env
#    deploy:
#     replicas: 1
#     restart_policy:
#       condition: on-failure
#     placement:
#       constraints:
#         - node.role == worker