services:
  front:
    image: ${IMAGE_REGISTRY_URL}:latest
    ports:
      - "8081:80"
    env_file:
      - stack.env
    networks:
     - frontend-net
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
     placement:
       constraints:
         - node.role == worker

networks:
 frontend-net:
   external:
     true
