services:
  front:
    image: ${IMAGE_REGISTRY_URL}:{IMAGE_REGISTRY_TAG:-dev}
    ports:
      - "8081:80"
    environment:
      - VITE_BASE_API_URL=${VITE_BASE_API_URL}
      - IMAGE_REGISTRY_URL=${IMAGE_REGISTRY_URL}
      - IMAGE_REGISTRY_TAG=${IMAGE_REGISTRY_TAG:-dev}
    env_file:
      - ../.env
    networks:
     - frontend-net

networks:
 frontend-net:
   